services: 
  app:
    build: .
    container_name: ${PROJECT_NAME}-api
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/${DB_NAME}
    volumes:
      - .:/app
      - /app/node_modules
  
  mongo:
    image: mongo:latest
    container_name: ${PROJECT_NAME}-mongo
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    